project:
  type: book
  output-dir: _book

bibliography: references.bib

book:
  title: "Trusted Mini-Agents"
  subtitle: "Engineering AI Errors Out of Agentic Workflows"
  author:
    - name: "Will Landau"
    - name: "Sam Parmar"
  date: 2026-08-28
  site-url: https://trustedminiagents.dev
  description: >
    A guide to engineering AI errors out of agentic workflows.
    Includes human-in-the-loop guardrails
    and agentic workflows in R and Shiny.
  image: images/social/og.png
  open-graph: true
  twitter-card: true
  search: true
  repo-url: https://github.com/wlandau/trustedminiagents
  repo-actions: [edit]
  repo-branch: main
  sidebar:
    style: docked
    logo: images/logo/1810x2090.png
  page-footer:
    left: "© 2026 Eli Lilly and Company"
  chapters:
    - index.qmd
    - part: "Concepts"
      chapters:
        - agents.qmd
        - errors.qmd
        - definition.qmd
    - part: "Implementation in R"
      chapters:
        - template.qmd
        - weather.qmd
        - simulation.qmd
    - part: "Implementation in Python"
      chapters:
        - template-py.qmd
        - weather-py.qmd
  appendices:
    - examples.qmd

format:
  html:
    canonical-url: true
    favicon: images/logo/favicon.png
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    code-link: false
    callout-appearance: simple
    mermaid:
      theme: neutral
